# Generated by Django 5.1.4 on 2025-01-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_uploaded_at_marinespecies_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marinespecies',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='marinespecies',
            name='species_data',
        ),
        migrations.AddField(
            model_name='marinespecies',
            name='class_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marinespecies',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='marinespecies',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marinespecies',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
