# Generated by Django 5.1.4 on 2025-01-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_marinespecies_image_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marinespecies',
            name='image_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
